[package]
name = "twitter_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.1.0"
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
egg-mode = "0.16.0"
egui = "0.16.1"
egui-winit = "0.16.0"
egui_glium = "0.16.0"
epi = "0.16.0"
futures = "0.3.19"
glium = "0.31.0"
image = "0.23.14"
lazy_static = "1.4.0"
log = "0.4.14"
open = "2.0.2"
pretty_env_logger = "0.4.0"
reqwest = "0.11.9"
serde = { version = "1.0.133", features = ["derive"] }
tokio = { version = "1.15.0", features = ["time", "macros"] }
toml = "0.5.8"
winit = "0.26.1"
